"""Utilities for gravitational-wave lensing calculations.

The functions in this module operate on frequency-domain waveforms.  They are
kept separate from :mod:`pyLensLib.gwsource` so that amplification factors can
be tested and reused without constructing a full source object.
"""

import numpy as np
from astropy import constants as const
from astropy import units as u
from scipy import special


GMSUN_C3_S = (const.G * const.M_sun / const.c**3).to_value(u.s)


def _hyp1f1_complex_series(a, b, z, tol=1.0e-12, max_terms=10000):
    """Evaluate 1F1(a; b; z) for complex arrays with a direct series."""
    a, z = np.broadcast_arrays(np.asarray(a, dtype=np.complex128), np.asarray(z, dtype=np.complex128))
    out = np.empty(a.shape, dtype=np.complex128)

    for index in np.ndindex(a.shape):
        aa = a[index]
        zz = z[index]
        term = 1.0 + 0.0j
        total = 1.0 + 0.0j
        for n in range(1, max_terms + 1):
            term *= (aa + n - 1.0) / (b + n - 1.0) * zz / n
            total_next = total + term
            if abs(term) <= tol * max(1.0, abs(total_next)):
                total = total_next
                break
            total = total_next
        out[index] = total

    return out


def chirp_mass(m1, m2):
    """Return the binary chirp mass in solar masses."""
    m1 = float(m1)
    m2 = float(m2)
    return (m1 * m2) ** (3.0 / 5.0) / (m1 + m2) ** (1.0 / 5.0)


def dimensionless_frequency(frequencies, mass_msun, zl=0.0):
    """Return the point-lens wave-optics frequency ``w``.

    Parameters
    ----------
    frequencies : array-like
        GW frequencies in Hz.
    mass_msun : float
        Lens mass in solar masses.
    zl : float, optional
        Lens redshift.  The redshifted mass is ``(1 + zl) * mass_msun``.
    """
    frequencies = np.asarray(frequencies, dtype=float)
    mass_msun = np.asarray(mass_msun, dtype=float)
    zl = np.asarray(zl, dtype=float)
    return 8.0 * np.pi * GMSUN_C3_S * mass_msun * (1.0 + zl) * frequencies


def newtonian_fd_waveform(
    frequencies,
    m1=30.0,
    m2=30.0,
    zs=0.0,
    luminosity_distance=None,
    amplitude=1.0,
    phase0=0.0,
    tc=0.0,
):
    """Generate a simple leading-order frequency-domain inspiral waveform.

    This is intentionally lightweight.  It is useful for simulations, tests,
    and examples, while production analyses can pass a waveform generated by
    PyCBC, LALSuite, Bilby, or another waveform package.
    """
    frequencies = np.asarray(frequencies, dtype=float)
    strain = np.zeros_like(frequencies, dtype=np.complex128)
    valid = frequencies > 0.0
    if not np.any(valid):
        return strain

    mc_z_s = chirp_mass(m1, m2) * (1.0 + float(zs)) * GMSUN_C3_S
    phase = (
        2.0 * np.pi * frequencies[valid] * float(tc)
        - float(phase0)
        - 0.25 * np.pi
        + (3.0 / 128.0) * (np.pi * mc_z_s * frequencies[valid]) ** (-5.0 / 3.0)
    )

    amp = float(amplitude) * frequencies[valid] ** (-7.0 / 6.0)
    if luminosity_distance is not None:
        amp = amp / float(luminosity_distance)
    strain[valid] = amp * np.exp(1j * phase)
    return strain


def weak_lensing_amplification(mu):
    """Return the GW strain amplification for a scalar lensing magnification."""
    return np.sqrt(np.abs(mu))


def morse_indices_from_lens_fields(kappa, gamma1, gamma2):
    """Infer Morse indices from local convergence and shear.

    The convention is 0 for minima, 1 for saddles, and 2 for maxima.  The input
    arrays are broadcast using NumPy rules.
    """
    kappa = np.asarray(kappa, dtype=float)
    gamma = np.hypot(gamma1, gamma2)
    lambda_t = 1.0 - kappa - gamma
    lambda_r = 1.0 - kappa + gamma

    morse = np.zeros(np.broadcast(lambda_t, lambda_r).shape, dtype=int)
    morse[(lambda_t * lambda_r) < 0.0] = 1
    morse[(lambda_t < 0.0) & (lambda_r < 0.0)] = 2
    return morse


def geometric_optics_amplification(
    frequencies,
    magnifications,
    delays,
    morse_indices=None,
    normalize_delays=True,
):
    """Return the geometric-optics GW amplification factor.

    Parameters
    ----------
    frequencies : array-like
        Frequencies in Hz.
    magnifications : array-like
        Signed image magnifications.
    delays : array-like
        Image arrival times in seconds.
    morse_indices : array-like, optional
        Morse indices for the images.  If omitted, positive signed
        magnifications are treated as minima and negative magnifications as
        saddles.
    normalize_delays : bool, optional
        If True, subtract the earliest arrival before applying phases.
    """
    frequencies = np.asarray(frequencies, dtype=float)
    magnifications = np.asarray(magnifications, dtype=float)
    delays = np.asarray(delays, dtype=float)

    if magnifications.size == 0:
        return np.zeros_like(frequencies, dtype=np.complex128)
    if delays.shape != magnifications.shape:
        raise ValueError("delays and magnifications must have the same shape")

    if morse_indices is None:
        morse_indices = np.where(magnifications < 0.0, 1, 0)
    morse_indices = np.asarray(morse_indices, dtype=int)
    if morse_indices.shape != magnifications.shape:
        raise ValueError("morse_indices and magnifications must have the same shape")

    if normalize_delays:
        delays = delays - np.nanmin(delays)

    amp = np.zeros_like(frequencies, dtype=np.complex128)
    for mu, delay, morse in zip(magnifications, delays, morse_indices):
        amp += np.sqrt(np.abs(mu)) * np.exp(
            2j * np.pi * frequencies * delay - 0.5j * np.pi * int(morse)
        )
    return amp


def point_mass_image_properties(y):
    """Return signed magnifications and Morse indices for a point-mass lens."""
    y = float(np.abs(y))
    if y == 0.0:
        y = np.finfo(float).eps
    root = np.sqrt(y * y + 4.0)
    common = (y * y + 2.0) / (2.0 * y * root)
    magnifications = np.array([0.5 + common, 0.5 - common], dtype=float)
    morse_indices = np.array([0, 1], dtype=int)
    return magnifications, morse_indices


def point_mass_time_delay_difference(mass_msun, y, zl=0.0):
    """Return the relative delay between point-mass images in seconds."""
    y = float(np.abs(y))
    if y == 0.0:
        y = np.finfo(float).eps
    root = np.sqrt(y * y + 4.0)
    tau = 0.5 * y * root + np.log((root + y) / (root - y))
    return 4.0 * GMSUN_C3_S * float(mass_msun) * (1.0 + float(zl)) * tau


def point_mass_geometric_amplification(frequencies, mass_msun, y, zl=0.0):
    """Return the geometric-optics amplification for a point-mass lens."""
    magnifications, morse_indices = point_mass_image_properties(y)
    delays = np.array([0.0, point_mass_time_delay_difference(mass_msun, y, zl=zl)])
    return geometric_optics_amplification(
        frequencies,
        magnifications,
        delays,
        morse_indices=morse_indices,
        normalize_delays=False,
    )


def point_mass_wave_amplification(frequencies, mass_msun, y, zl=0.0):
    """Return the analytic wave-optics amplification for a point-mass lens.

    The expression follows the standard frequency-domain amplification factor
    for a point lens.  Frequencies are in Hz and mass is in solar masses.
    """
    frequencies = np.asarray(frequencies, dtype=float)
    y = float(np.abs(y))
    if y == 0.0:
        y = np.finfo(float).eps

    w = dimensionless_frequency(frequencies, mass_msun, zl=zl)
    amp = np.ones_like(w, dtype=np.complex128)
    valid = w > 0.0
    if not np.any(valid):
        return amp

    root = np.sqrt(y * y + 4.0)
    x_m = 0.5 * (y + root)
    phi_m = 0.5 * (x_m - y) ** 2 - np.log(x_m)
    wv = w[valid]

    log_prefactor = (
        0.25 * np.pi * wv
        + 0.5j * wv * (np.log(0.5 * wv) - 2.0 * phi_m)
        + special.loggamma(1.0 - 0.5j * wv)
    )
    hyper = _hyp1f1_complex_series(0.5j * wv, 1.0, 0.5j * wv * y * y)
    amp[valid] = np.exp(log_prefactor) * hyper
    return amp


def point_mass_regime(
    frequencies,
    mass_msun,
    zl=0.0,
    wave_threshold=10.0,
    geo_threshold=100.0,
):
    """Choose ``wave``, ``hybrid``, or ``geometric`` for a point-mass lens."""
    w = dimensionless_frequency(frequencies, mass_msun, zl=zl)
    w = w[np.isfinite(w) & (w > 0.0)]
    if w.size == 0:
        return "wave"
    if np.nanmax(w) <= float(wave_threshold):
        return "wave"
    if np.nanmin(w) < float(geo_threshold):
        return "hybrid"
    return "geometric"


def point_mass_einstein_radius_arcsec(mass_msun, zl, zs, cosmology):
    """Return the point-mass Einstein radius in arcsec."""
    if zs <= zl:
        return 0.0
    mass = float(mass_msun) * const.M_sun
    dl = cosmology.angular_diameter_distance(zl)
    ds = cosmology.angular_diameter_distance(zs)
    dls = cosmology.angular_diameter_distance_z1z2(zl, zs)
    length = (4.0 * const.G * mass / const.c**2).to(dl.unit)
    theta_rad = np.sqrt((length * dls / (dl * ds)).decompose().value)
    return (theta_rad * u.rad).to_value(u.arcsec)
